### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by swakhandekar** [ATNF/yandasoft#10]
Hi team,

I am setting up a development environment for Yandasoft.

For this I have set up a fresh Ubuntu 18.04, with all the latest updates.
cmake version: 3.16.5

For the setup, I am following instructions from [INSTALL.md](https://github.com/ATNF/yandasoft/blob/master/INSTALL.md).
After following the steps, I was able to install all the system dependencies and internal askap dependencies.

I am getting error in the build of yandasoft itself.
Following is the first error that I encountered without any change in source:
[error1.txt](https://github.com/ATNF/yandasoft/files/4327963/error1.txt)

I observed that the file that cmake is trying to find is available but with a different name under askap-cmake directory. Hence I changed the name of packages one by one.
After each name change cmake was able to map the correct dependency.
Changes that I made in CMakeList.txt:
[cmakeChange.txt](https://github.com/ATNF/yandasoft/files/4327967/cmakeChange.txt)

Finally after all the changes, I got the following error which I am unable to resolve:
[error2.txt](https://github.com/ATNF/yandasoft/files/4327968/error2.txt)

Can you please let me know if I am missing anything and help me in getting this setup done?

**Comment by prlahur** [comment]
Thanks for posting the issue, Swapnil. We'll try to reproduce this error. Let's see what happens.

**Comment by steve-ord** [comment]
Hiya

This error has been caused by the askap-cmake directory being out-of-sync with the yandasoft directory and some of its dependencies. This is not your fault. If you pull the develop branch of the dependencies instead of master - you should get everything in sync. If you add the "-d" flag to build_all.sh this <should> happen automatically.

**Comment by prlahur** [comment]
@steve-ord , is the build_all.sh itself missing?

**Comment by steve-ord** [comment]
Should not be .... have you pulled the "develop" branch?

**Comment by steve-ord** [comment]
I think its in deploy/general. I haven't built it that way in a while as I trust the containers these days ;-)

**Comment by prlahur** [comment]
Same here, I've been using container a lot ... 
Yes, you're right. It's in Git branch "develop", inside dir "deploy/general"

**Comment by swakhandekar** [comment]
Thanks @prlahur and @steve-ord for your quick response, I just did a clean start with your suggestions and it worked for me. Thanks a lot again!

**Comment by prlahur** [comment]
You're welcome, @swakhandekar, and thanks, @steve-ord .
I'll update the the wiki and INSTALL.md accordingly.
