### ISSUE TITLE
issue when trying to pull the latest singularity image

### ISSUE THREAD

**Issue by westjl** [ATNF/yandasoft#16]
I am just trying to update my singularity image. I do:

`singularity pull docker://csirocass/yandasoft:openmpi4`

But I am currently getting this error:

`FATAL:   While making image from oci registry: error fetching image to cache: failed to get checksum for docker://csirocass/yandasoft:openmpi4: Error reading manifest openmpi4 in docker.io/csirocass/yandasoft: manifest unknown: manifest unknown`

**Comment by westjl** [comment]
Oh, got it working with:

`singularity pull docker://csirocass/yandasoft:1.1-openmpi4`

Perhaps the wiki page should be updated:

https://github.com/ATNF/yandasoft/wiki/How-to-install-using-container

**Comment by prlahur** [comment]
Thanks, @westjl . I updated the wiki page just now.
