### ISSUE TITLE
add documentation

### ISSUE THREAD

**Issue by steve-ord** [ATNF/yandasoft#5]
The ASKAPSOft docs are built from a subdirectory off trunk that I haven't taken. I'm wondering whether to take that and build it all the same way

**Comment by mattwhiting** [comment]
Code/Docs has documentation for all sorts of stuff, not just synthesis but also analysis, ingest & the pipeline scripts. As well as platform-specific details for running & interacting with things on Pawsey.
I don't know whether we want to separate out the docs for each repo, and then have something that brings them together (so we can easily create the full set), or instead keep the docs in a single place as for now.

**Comment by steve-ord** [comment]
I've created an askap-docs bitbucket that mirrors the SVN. The git version of this is included as a submodule and I have edited the index.rst to only include docs relevant to YandaSoft. This <should work> One issue is that the svn mirror does not auto-magically merge with the GitHub,

It may make sense to instead of having branches - just have index.rst that are project specific - but all docs reside in the same place.
